<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Method\Form */ ?>
<?php $_shippingRateGroups = $block->getShippingRates(); ?>
<?php if ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" style="display:none">
        <dl class="admin__order-shipment-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt class="admin__order-shipment-methods-title"><?php echo $block->escapeHtml($block->getCarrierName($code)) ?></dt>
                <dd class="admin__order-shipment-methods-options">
                    <ul class="admin__order-shipment-methods-options-list">
                        <?php foreach ($_rates as $_rate): ?>
                            <?php $_radioProperty = 'name="order[shipping_method]" type="radio" onclick="order.setShippingMethod(this.value)"' ?>
                            <?php $_code = $_rate->getCode() ?>
                            <li class="admin__field-option">
                                <?php if ($_rate->getErrorMessage()): ?>
                                    <div class="messages">
                                        <div class="message message-error error">
                                            <div><?php echo $block->escapeHtml($_rate->getErrorMessage()) ?></div>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <?php $_checked = $block->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                                    <input <?php /* @escapeNotVerified */ echo $_radioProperty ?> value="<?php /* @escapeNotVerified */ echo $_code ?>"
                                                                                                  id="s_method_<?php /* @escapeNotVerified */ echo $_code ?>" <?php /* @escapeNotVerified */ echo $_checked ?>
                                                                                                  class="admin__control-radio"/>
                                    <label class="admin__field-label" for="s_method_<?php /* @escapeNotVerified */ echo $_code ?>">
                                        <?php echo $block->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
                                        <strong>
                                            <?php $_excl = $block->getShippingPrice($_rate->getPrice(), $this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()); ?>
                                            <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                                            <?php /* @escapeNotVerified */ echo $_excl; ?>
                                            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
                                            <?php endif; ?>
                                        </strong>
                                    </label>
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
    <?php if ($_rate = $block->getActiveMethodRate()): ?>
        <div id="order-shipping-method-info" class="order-shipping-method-info">
            <dl class="admin__order-shipment-methods">
                <dt class="admin__order-shipment-methods-title">
                    <?php echo $block->escapeHtml($block->getCarrierName($_rate->getCarrier())) ?>
                </dt>
                <dd class="admin__order-shipment-methods-options">
                    <?php echo $block->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
                    <strong>
                        <?php $_excl = $block->getShippingPrice($_rate->getPrice(), $this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                        <?php /* @escapeNotVerified */ echo $_excl; ?>
                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
                        <?php endif; ?>
                    </strong>
                </dd>
            </dl>
            <a href="#"
               onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false"
               class="action-default">
                <span><?php /* @escapeNotVerified */ echo __('Click to change shipping method') ?></span>
            </a>
        </div>
    <?php else: ?>
        <script>
            require(['prototype'], function(){
                $('order-shipping-method-choose').show();
            });
        </script>
    <?php endif; ?>
<?php elseif ($block->getIsRateRequest()): ?>
    <div class="order-shipping-method-summary">
        <strong class="order-shipping-method-not-available"><?php /* @escapeNotVerified */ echo __('Sorry, no quotes are available for this order.') ?></strong>
    </div>
<?php else: ?>
    <div id="order-shipping-method-summary" class="order-shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false" class="action-default">
            <span><?php /* @escapeNotVerified */ echo __('Get shipping methods and rates') ?></span>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
    </div>
<?php endif; ?>
<div style="display: none;" id="shipping-method-overlay" class="order-methods-overlay">
    <span><?php /* @escapeNotVerified */ echo __('You don\'t need to select a shipping method.') ?></span>
</div>
<script>
    require(["Magento_Sales/order/create/form"], function(){

        order.overlay('shipping-method-overlay', <?php if ($block->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
        order.overlay('address-shipping-overlay', <?php if ($block->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);

        <?php if ($block->getQuote()->isVirtual()): ?>
        order.isOnlyVirtualProduct = true;
        <?php endif; ?>
    });
</script>

<!-- delivery date field -->
<style>
    ._has-datepicker ~ .ui-datepicker-trigger {
        background-image: none;
        background: none;
        -moz-box-sizing: content-box;
        border: 0;
        box-shadow: none;
        line-height: inherit;
        margin: 0;
        padding: 0;
        text-shadow: none;
        font-weight: 400;
        display: block;
        text-decoration: none;
        display: inline-block;
        margin-top: -4px;
        vertical-align: middle;
    }
    ._has-datepicker ~ .ui-datepicker-trigger:focus,
    ._has-datepicker ~ .ui-datepicker-trigger:active {
        background: none;
        border: none;
    }
    ._has-datepicker ~ .ui-datepicker-trigger:hover {
        background: none;
        border: none;
    }
    ._has-datepicker ~ .ui-datepicker-trigger.disabled,
    ._has-datepicker ~ .ui-datepicker-trigger[disabled],
    fieldset[disabled] ._has-datepicker ~ .ui-datepicker-trigger {
        cursor: not-allowed;
        pointer-events: none;
        opacity: 0.5;
    }
    ._has-datepicker ~ .ui-datepicker-trigger > span {
        border: 0;
        clip: rect(0, 0, 0, 0);
        height: 1px;
        margin: -1px;
        overflow: hidden;
        padding: 0;
        position: absolute;
        width: 1px;
    }
    ._has-datepicker ~ .ui-datepicker-trigger:before {
        -webkit-font-smoothing: antialiased;
        font-size: 23px;
        line-height: 23px;
        color: #7d7d7d;
        content: '\e612';
        font-family: 'luma-icons';
        vertical-align: middle;
        display: inline-block;
        font-weight: normal;
        overflow: hidden;
        speak: none;
        text-align: center;
    }
    ._has-datepicker ~ .ui-datepicker-trigger:focus {
        box-shadow: none;
        outline: 0;
    }
</style>

<div class="required delivery-date">
    <label class="label" for="delivery_date">
        <span>Delivery date</span>
    </label>
    <div class="control">
        <input style="position: relative;margin-right: 10px;width: calc(100% - 33px);" readonly="readonly"
               type="date" id="delivery_date" value=""
               placeholder="YYYY-MM-DD" aria-required="false"
               class="input-text "
               name="delivery_date">
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        'mage/url',
        "mage/calendar",
        "Magento_Sales/order/create/form"
    ], function($, url){

        $("#delivery_date").datepicker("destroy");
        $("#delivery_date").datepicker(
            {
                minDate: new Date(),
                dateFormat: 'yy-mm-dd'
            });

        $("#delivery_date").change(function () {
            var date = $("#delivery_date").val();

            $.ajax({
                url: url.build("../../../../../inventorysuccess/deliveryDate/saveSession"),
                type: "post",
                dateType: "json",
                showLoader: true,
                data: {
                    deliveryDate: date
                },
                success: function (result) {

                },
                always: function () {

                }
            });
        });

        if($("#delivery_date").val() == null || $("#delivery_date").val() == '') {
            $("#delivery_date").val($.datepicker.formatDate('yy-mm-dd', new Date())).trigger('change');
        } else {
            $("#delivery_date").trigger('change');
        }
    })
</script>