<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="order-date">
    <?php /* @escapeNotVerified */ echo __('<span class="">Order Date:</span> %1', '<date>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</date>') ?>
</div>
<div class="order-date">
    <?php /* @escapeNotVerified */ echo __('<span class="">Delivery Date:</span> %1', '<date>' . $block->formatDate($block->getOrder()->getDeliveryDate(), \IntlDateFormatter::LONG) . '</date>') ?>
</div>
